spring.application.name=airfp


openrouter.api.key=${API_KEY}
openrouter.url=${API_URL}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.hibernate.ddl-auto=update



spring.mail.host=${SMTP_HOST}
spring.mail.port=${SMTP_PORT}
spring.mail.username=${SMTP_USERNAME}
spring.mail.password=${SMTP_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true



mail.imap.host=${IMAP_HOST}
mail.imap.port=${IMAP_PORT}
mail.imap.username=${IMAP_USERNAME}
mail.imap.password=${IMAP_PASSWORD}
mail.imap.ssl.enable=true

# Temporary folder for attachments
app.temp-dir=/tmp/rfp-attachments


